### ISSUE TITLE
Create Contribution.md file

### ISSUE THREAD

**Issue by Rohit-554** [Rohit-554/NewsAppFlutterCleanArtitecture#2]
Include everything 

* How one can fork 
* How clone it in local
* How he can start contribution 
* Git push, pull, clone, commit include these things

[Click for Demo](https://github.com/Rohit-554/statsHunter/blob/master/contribution.md)

**Comment by aumii01codes** [comment]
I want to contribute. I have worked on Readme files, so I know how to include the mentioned points. Please assign this issue to me.

**Comment by aumiidutta** [comment]
I want to contribute. I have worked with git commands and editing readme files so I know how to include the mentioned points. Please assign this issue to me.

**Comment by Rohit-554** [comment]
Sure, you can start you work, make sure to follow the demo

**Comment by dikshant182004** [comment]
hii @Rohit-554 plz assign this issue to me

**Comment by aumiidutta** [comment]
Thanks, I have started working on it!
